### PR TITLE
Optimised images

### PR DESCRIPTION
**Pull request by ricksterhd123**
*Total -- 687.97kb -> 586.16kb (14.8%)
Maybe not worth it?

### CODE REVIEW

**Comment by Dutchman101** [comment]
Thanks for the PR, but i am already working on this, although the reduction will be greater than 14.8% and there will be no changed pixels at all. Even then, it will be limited since we also did it in the past (using an inferior method) at 99a39b7

So stay tuned!

**Comment by ricksterhd123** [comment]
No problem, I am curious - is there any tools which can compress the images inside a .txd automatically?

**Comment by dmi7ry** [comment]
> No problem, I am curious - is there any tools which can compress the images inside a .txd automatically?

It can't be done automatically right, because such tool can't know what format is requred by each texture (for an example, some of them should be unpacked ARGB, otherwise GTA will be crashed, etc).

**Comment by Dutchman101** [comment]
Not that i know of, but for manually doing it, give this a read: [https://wiki.multitheftauto.com/wiki/Optimize_Custom_TXD](https://wiki.multitheftauto.com/wiki/Optimize_Custom_TXD)

**Pull request closed without merging**
