### PR TITLE
Add doc links to README

### PR DESCRIPTION
**Pull request by Fernando-A-Rocha**
The community started working on a new wiki article related to the mtasa-resources project, so I figured it would be useful to include links to that page, as well as the new Contributing guide on the main README.

- https://wiki.multitheftauto.com/wiki/Default_resources
- https://github.com/multitheftauto/mtasa-docs/blob/main/mtasa-resources/CONTRIBUTING.md

### CODE REVIEW

**Comment by Fernando-A-Rocha** [comment]
Putting this on standby because https://github.com/multitheftauto/mtasa-docs was created

**Comment by Fernando-A-Rocha** [comment]
Updated. Ready

**Comment by Fernando-A-Rocha** [comment]
Oops

**Comment by Fernando-A-Rocha** [comment]
@jlillis

**Review by Nico8340 — COMMENTED** [review]
LGTM

**Pull request merged**
