### PR TITLE
#359 Hedit delete handlings

### LINKED ISSUE #359: Hedit: delete handlings
**Is your feature request related to a problem? Please describe.**

There's no method for deleting handlings, except manually going into saves.xml file in the resources cache.

**Describe the solution you'd like**

I'd like to be able to select a handling and click a button to delete it.

**Describe alternatives you've considered**

Manual deletion in resources cache folder.

### PR DESCRIPTION
**Pull request by ricksterhd123**
This PR should close #359
We will need translations for Arabic, Polish, Russian, Spanish and Turkish. Can I use google translate?
I will make this a draft for now, I think I can get Arabic and Spanish but not the rest.

### CODE REVIEW

**Comment by Inder00** [comment]
I can help with polish!

**Comment by ricksterhd123** [comment]
> I can help with polish!
Awesome, do you want to submit a PR on my fork and I will merge you?
This line here needs to be translated from English to Polish the sentence: "Successfully deleted your handling settings!"

You can edit in github:
https://github.com/ricksterhd123/mtasa-resources/blob/hedit-delete-handlings/%5Bgameplay%5D/hedit/client/gui/languages/polish.lua#L39

**Comment by Dutchman101** [comment]
For this resource, it will be unmanagable to go through pain and a lot of delays (getting a translation for every feature that adds a new button/text) every time someone contributes a new feature. So im in favour of either:

- Autotranslate the required text, so it can be merged. Then put it on a list of "unverified translations" that need to be checked off/improved on by a native speaker
- Don't translate it, so it can be merged. Then put it on a list of "pending translations" (untranslated buttons/texts) for hedit localisation

Any thoughts?

**Comment by ricksterhd123** [comment]
Russian translation is done via Google Translate. Not sure where I can add this to "pending translations". Ready for review.

**Review by jlillis — CHANGES_REQUESTED** [review]
The updated translations should be addressed in a separate PR from the original changes proposed by this PR originally.

**Review by ricksterhd123 — COMMENTED** [review]
Moved all translations into separate PR

**Review by jlillis — APPROVED** [review]

**Pull request merged**
