### PR TITLE
[playerblips] Added team functionality

### PR DESCRIPTION
**Pull request by nokizorque**
- Added team functionality, with an optional switch.
- Settings for blip size and alpha.

### CODE REVIEW

**Comment by qaisjp** [comment]
Thank you for your contribution! The code looks fine from here, but I'll get this tested by the end of the week.

**Comment by qaisjp** [comment]
I've tested and looked through your update and there are a few things that need improving/fixing:
* an error message when a player is not in a team
* team colour needs to default to off (to behave the same out of the box)
* disabling both commands when in team mode (custom colours and team colours mixed sound a bit problematic design wise, IMO)

I think supporting all the different cases would make the resource unnecessarily complex and I don't think that this resource really needs these features and settings right now.

If you can address these issues and explain why you feel that these features should be available then feel free to reopen this pull request, but for now I am closing this pull request.

Thanks again :)

**Comment by nokizorque** [comment]
> - an error message when a player is not in a team

Yeah, that was a poor move on my part.

> - team colour needs to default to off (to behave the same out of the box)
- disabling both commands when in team mode

Fixed!

In the first line of the current playerblips.lua, it says:
> needs configurable blip colors, and team support

I still wanted to preserve the original functionality and add this new functionality. I didn't think of the mixed types though. I guess I'll need to do that better next time.

**Comment by qaisjp** [comment]
Perhaps you could allow those features/settings to be configured using the settings system?

This allows administrators to change the team mode using the admin panel.

**Pull request closed without merging**
