### PR TITLE
race: Change the start of countdown from 6 to 3

### LINKED ISSUE #214: race: missing countdown images
**Which resource(s) have this problem?**
race

**Describe the bug**
The race resource is missing countdown images 6.png, 5.png, and 4.png, resulting in errors.

**To Reproduce**
1. Start a race
2. Watch debugscript

**Log entries**
`WARNING: race\countdown_client.lua:60: File not found @ 'guiCreateStaticImage' [img/countdown_6.png]

WARNING: race\countdown_client.lua:60: File not found @ 'guiCreateStaticImage' [img/countdown_5.png]

WARNING: race\countdown_client.lua:60: File not found @ 'guiCreateStaticImage' [img/countdown_4.png]`

**Version:**
- server/client 1.5.7 stale
- mtasa-resources master (as of writing)

**Additional context**
To fix this, we could either a: find (or make) the missing images and add them or b: shorten the countdown to just 3 seconds.

### PR DESCRIPTION
**Pull request by xLivex**
Fixes #214 
btw i didn't find any clue why it's 6 seconds maybe a mistake?
i couldn't find any images to 4,5,6 in old versions, 
even the code it plays a sound 4 times instead of 6
`g_RaceStartCountdown:addClientHook(3, 'playSoundFrontEnd', 44)
g_RaceStartCountdown:addClientHook(2, 'playSoundFrontEnd', 44)
g_RaceStartCountdown:addClientHook(1, 'playSoundFrontEnd', 44)
g_RaceStartCountdown:addClientHook(0, 'playSoundFrontEnd', 45)`

### CODE REVIEW

**Comment by AfuSensi** [comment]
Maybe instead of hardcoding this, we could have a setting instead.

**Comment by zo3n** [comment]
> It's like the 3 seconds are just to have players really prepared.

No, because that's what "Waiting for players..." text is for. Also, (i might be wrong) but it gives out warnings that images of countdown 4-6 don't exist in debugscript 3

**Comment by jlillis** [comment]
If nobody can find the missing images (did they ever exist?) then I think merging this PR would be the simplest solution for fixing this error. Adding a setting could be done in response to a feature request some other time.

**Comment by qaisjp** [comment]
Thank you!

**Pull request merged**
