### PR TITLE
add sex, dance and blowjob animations

### PR DESCRIPTION
**Pull request by JohnFlowerful**
Are they allowed?

### CODE REVIEW

**Comment by Disinterpreter** [comment]
it's animations doesn't work on Steam version. (it's only hot coffee mode)

**Comment by qaisjp** [comment]
It appears the line endings have been changed. Please force push an update fixing this.

**Comment by ccw808** [comment]
How many players have the Steam version?

**Comment by ArranTuna** [comment]
Unfortunately setPedAnimation returns true even if the animation is false so can't use that to find out how many players have these animations. Can MTA tell what versions of the game people use?

**Comment by Jusonex** [comment]
I'm closing this due to the Steam version issue.

**Pull request closed without merging**
