### PR TITLE
Added client side file for missiontimer fix PR

### PR DESCRIPTION
**Pull request by Einheit-101**
Sorry, couldnt find any button to merge this file into the existing PR.
This is, hands down, the worst and most unintuitive web page i've ever had to use.

### CODE REVIEW

**Comment by Einheit-101** [comment]
There are still 2 files missing that needed a change. I really dont want to put up another PR for these 2 files ^^

**Comment by qaisjp** [comment]
...? Is this an addendum to #44?

**Comment by Einheit-101** [comment]
Yes, and i still have 2 more files to change.

**Comment by PhrozenByte** [comment]
@Einheit-101: This PR corresponds to the `patch-5` branch of your fork. Simply select the branch of [your fork](https://github.com/Einheit-101/mtasa-resources) ([direct link to the `patch-5` branch](https://github.com/Einheit-101/mtasa-resources/tree/patch-5)) and edit the files appropriately (e.g. [`[gameplay]/missiontimer/missiontimer_client.lua`](https://github.com/Einheit-101/mtasa-resources/edit/patch-5/[gameplay]/missiontimer/missiontimer_client.lua)). Add a edit notice below, hit `Save` and the commit (i.e. your change) appears in this PR automatically.

**Pull request closed without merging**
