### PR TITLE
Added weapons table to replace old method

### PR DESCRIPTION
**Pull request by alberto2345**
- Replaced the old method of retrieving weapon names with a table to get
rid of bad weapon names such as Bomb and Freefalling Bomb and duplicated Dildo and Vibrator names. (temp fix until getWeaponNameFromID is fixed)

### CODE REVIEW

**Comment by qaisjp** [comment]
> temp fix until getWeaponNameFromID is fixed

Please can you link the bug report for that function?

**Comment by alberto2345** [comment]
https://bugs.mtasa.com/view.php?id=7968

It doesn't say anything about the IDs that say Bomb and Freefalling bomb though.

**Comment by qaisjp** [comment]
Please add a note to the report describing those other problems.

**Comment by alberto2345** [comment]
Ok no problem, I added a note to the issue.

**Comment by qaisjp** [comment]
A better solution would be to blacklist projectile IDs.

**Pull request closed without merging**
