### PR TITLE
Add favorite models and last used

### PR DESCRIPTION
**Pull request by CrosRoad95**
This pr add option to save favorite models, and add list of last used models
To rename favorite model, press right button on ❤ icon

### CODE REVIEW

**Comment by CrosRoad95** [comment]
indentations fixed :)

**Comment by Woovie** [comment]
Is this ready for commit? I think it offers some useful features.

**Comment by jlillis** [comment]
I know it's been over two years, but I'm prepared to merge this if:
1 - you can resolve merge conflicts
2 - tweak the grammar of the rename input box to something like "Enter a new name for this model:"
3 - maybe add some sort of indication that you can rename a favorite model, and that a model has been renamed. The only way someone would be aware of this feature currently is by seeing this PR.

**Comment by jlillis** [comment]
Going to close this for now after 3 months of inactivity. Feel free to reopen when this is ready for merge.

**Pull request closed without merging**
