### PR TITLE
admin: screenshot tweaks

### PR DESCRIPTION
**Pull request by theSarrum**
When merged, this PR will:
- Optimize bandwidth usage by using the _client_ global variable instead of passing the player by parameter.
- Fix permission checking by using an existing action name.

### CODE REVIEW

**Comment by Dezash** [comment]
I think it would be better to add the `takescreenshot` permission to the default ACL configuration rather than remove it

**Comment by theSarrum** [comment]
> I think it would be better to add the `takescreenshot` permission to the default ACL configuration rather than remove it

I thought about it, but decided that it makes no sense to restrict screenshots for certain ACL groups, because they do not contain any private information.
Then there are 2 options:
1. Add one permission (`command.screenshots`?) that will block full access to screenshots
2. Add different permissions for different actions:
2.1. 'Take New' - `command.takescreenshot`
2.2. 'Delete' - `command.deletescreenshot`
2.3. 'View' - `command.viewscreenshot`
2.4. 'Refresh' - `command.listscreenshots`

**Comment by Dezash** [comment]
More granular permissions are better in my opinion. You may not want trial moderators deleting screenshots or sometimes even taking them. However, the mentioned permissions should use "general" prefix instead of "command".

**Comment by theSarrum** [comment]
I agree with the prefix, but if we want to block buttons, there is no other option.
https://github.com/multitheftauto/mtasa-resources/blob/44053e2c7b59b84183cf1a349822c853354aa76f/%5Badmin%5D/admin/client/admin_gui.lua#L43

**Comment by Pirulax** [comment]
I think you should be able to change the triggers on client side to be `localPlayer` instead of `resoureRoot`.

**Comment by theSarrum** [comment]
I have made changes, now we can restrict the rights for certain groups.

> I think you should be able to change the trigger sources on client side to be `localPlayer` instead of `resoureRoot`, then just attach the handler to root on the server side.

Not sure if this is necessary. But if others agree, I'll do it.
Also weird that then we will have to attach to `root` on the server instead of `resourceRoot`.

**Comment by srslyyyy** [comment]
> Not sure if this is necessary. But if others agree, I'll do it.
Why not. Would be nice to follow this in any upcoming PR, if possible.

**Comment by theSarrum** [comment]
> Why not. Would be nice to follow this in any upcoming PR, if possible.

Done.

**Review by jlillis — APPROVED** [review]

**Pull request merged**
