### PR TITLE
deathmatch: additional improvements

### PR DESCRIPTION
**Pull request by jlillis**
This PR makes additional improvements to the new `deathmatch` resource:

- Fixes a bug I introduced in #519. Whoops.
- Adds a round start timer
- Disables the area name HUD (dm maps are often made high above the map, area name is not relevant)
- Fixes next round not starting when `mapcycler` isn't running
- Adds spectator mode
- Adds element data protections

### CODE REVIEW

**Review by Nico8340 — COMMENTED** [review]
So far so good

**Comment by Dutchman101** [comment]
Is it about ready for review, @jlillis ?

**Comment by jlillis** [comment]
I had a few other things to add and one last round of clean up in mind. Hoping to have some free time this weekend to wrap up.

**Comment by jlillis** [comment]
Going to call this ready for review now. Would be nice to see it play-tested with more than myself and a VM to make sure everything works.

**Comment by Dutchman101** [comment]
I don't see any problems, but due to how niche "deathmatch" is, there is no better way to actually have it playtested than to put it out there. So merging the PR, to be subject to bug reports/addendums by later suggestion.

**Pull request merged**
