### PR TITLE
Delete cdm resource

### PR DESCRIPTION
**Pull request by jlillis**
When merged, this PR will delete the cdm (classic death match) resource. The justification for this is:

1. This particular resource is very old and only ships with one map
2. There do not appear to be any servers running this gamemode at the moment
3. The gameplay style implemented by this resource (and it's one map) is also implemented by other gamemodes which are actively played and maintained.

### CODE REVIEW

**Comment by qaisjp** [comment]
Most resources that use [cdm on community](https://community.mtasa.com/index.php?p=resources&s=details&id=68) were written in 2008, one in 2009, one in 2010, and one in 2015.

Checking the MTA database indeed there are no servers running this gamemode at the moment.

**Comment by jlillis** [comment]
I've uploaded the `cdm-ls` map to the community site at https://community.multitheftauto.com/index.php?p=resources&s=details&id=18319.

**Comment by Disinterpreter** [comment]
> 1. This particular resource is very old and only ships with one map 

There aren't reasons for map at this gamemode

> 2. There do not appear to be any servers running this gamemode at the moment

As another gamemodes.

> 3. The gameplay style implemented by this resource (and it's one map) is also implemented by other gamemodes which are actively played and maintained.

The genre of this gamemode is pretty cool, but our cdm is poor. 
I can suggest to rewrite it and add more interesting features. 
If you really want refresh it I could make an issue with reworking cdm as a concept.

**Comment by jlillis** [comment]
Sorry, but I do not think this resource is worth maintaining considering it's age and lack of popularity. The deathmatch genre is already covered by the deathmatch resource, which is undergoing a refactor as we speak. I am going to move forward with merging this as the changes have already been approved.

**Comment by Dutchman101** [comment]
> Before deletion I think we should upload the latest copy to the above resource (version number can probably be `1.5.7`, to match the MTA version).

Now that cdm-ls has been uploaded by @jlillis, i uploaded an update to the existing 'cdm' community resource, which is the latest version before removal + code style clean-up.  So, for those interested, the gamemode can still be found here: [https://community.multitheftauto.com/index.php?p=resources&s=details&id=68](https://community.multitheftauto.com/index.php?p=resources&s=details&id=68)

**Pull request merged**
