### PR TITLE
runcode: Add console logging for unauthorized HTTP users

### PR DESCRIPTION
**Pull request by xLuxy**
This PR (https://github.com/multitheftauto/mtasa-resources/pull/179) is an addition to the mentioned PR. It adds console logging for unauthorized users trying to execute lua code without permissions

//cc: @ccw808

### CODE REVIEW

**Comment by xLuxy** [comment]
Just noticed that i commited on my prev. branch which was unintended. I hope it's still fine and when not, lemme know.

**Comment by qaisjp** [comment]
Something is wrong with the diff. Maybe you've changed all the line endings?

**Comment by xLuxy** [comment]
> Something is wrong with the diff. Maybe you've changed all the line endings?

Just checked and nope, i didnt change line endings. Might be caused by the merge conflict which i resolved using "Resolve conflicts" on GitHub.

**Comment by qaisjp** [comment]
Line endings were previously CRLF. Now they are LF.

**Comment by xLuxy** [comment]
> Line endings were previously CRLF. Now they are LF.

thanks for chaning

**Pull request merged**
