### PR TITLE
Hedit delete button translations

### PR DESCRIPTION
**Pull request by ricksterhd123**
Once merged this PR will create translations for the delete handling functionality in hedit for all currently supported languages.

I've cherry picked the translation commits out of the PR #360 so that they can be addressed separately. 

Once #360 is merged, we might conflicts.

### CODE REVIEW

**Comment by jlillis** [comment]
I've merged #360 - when you feel you have as many translations as you think you're going to get for a while just mark this as ready and I'll review & merge.

**Review by Dutchman101 — DISMISSED** [review]
Please correct all typo's in this PR (as in commit 6509b74)

**Comment by ricksterhd123** [comment]
> Please correct all typo's in this PR (as in commit [6509b74](https://github.com/multitheftauto/mtasa-resources/commit/6509b7424c3c2d6b38054e86904cc5b9a9c7fa78))

Yes thank you for noticing this I know I wouldn't've ;p
I will *try* to pick it up later today. I've been procrastinating on this.

**Comment by ricksterhd123** [comment]
> Circling back on this - do you have any more updates/translations to add, or can we merge what is already here?

This got abandoned, so nothing in a long time. I'm not sure, I think it was, but let me see if it's still OK, and I'll get back.

**Review by ricksterhd123 — COMMENTED** [review]
Fixed typo requested by Dutch and added translations

**Comment by ricksterhd123** [comment]
@jlillis I did a quick test and the translations added work, this PR is ready now

**Pull request merged**
