### PR TITLE
Update for IPB resource

### PR DESCRIPTION
**Pull request by Necktrox**
**Changes**
- Dynamic window size, which depends on screen resolution
- Added support for client performance statistics
- Separated code base into multiple files
- Improved resource settings config
- Auto-sized statistic columns

## **1920x1080**
ipb

## **1280x720**
ipb

## **800x600**
ipb

## **640x480**
ipb

### CODE REVIEW

**Comment by qaisjp** [comment]
It would've been best to do the separation separately because right now we can't see what changes have been made.

**Comment by Necktrox** [comment]
I am not sure if that would've helped in any way, because most of the code has been changed.

**Comment by Dutchman101** [comment]
quite a few files with tabulation issues (empty, extra space on line 1)

**Comment by Necktrox** [comment]
@Dutchman101 I keep the first and last line empty as my own design choice. The last commit should fix the remaining indentation mistakes.

**Comment by Dutchman101** [comment]
100% stable

**Comment by qaisjp** [comment]
Thank you!

**Pull request merged**
